### ISSUE TITLE
ACT Overlays are not parsing correctly despite base ACT working fine

### ISSUE THREAD

**Issue by Tway1** [seathasky/FF14-MAC_ModSupport#27]
This is only happening when I'm in a party so the overlays work perfectly when I'm on the overworld or in an unsynced instance alone.
On Bunny-HUD I've tried both MopiMopi and Kagerou and have the same issue. 
I've followed the ACT setup using the WinPCap connection and have the same IP address and port in the Stream/Local Overlay tab.
The base ACT parses correctly, both in overworld and 4/8man content but it doesn't translate into the overlay. There are some errors in the OverlayPlugin.dll log which may be causing this but I'm not sure why... I've checked that the latest version is being used. Log below:

[23/11/2021 15:52:38] Info: WS: Error: System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at WebSocketSharp.WebSocket.sendBytes(Byte[] bytes) 
[23/11/2021 15:52:38] Info: WS: Error: System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at WebSocketSharp.WebSocket.sendBytes(Byte[] bytes) 
[23/11/2021 15:53:47] Error: Failed to send legacy WS message: System.InvalidOperationException: The current state of the connection is not Open.
   at WebSocketSharp.WebSocket.Send(String data)
   at WebSocketSharp.Server.WebSocketBehavior.Send(String data)
   at RainbowMage.OverlayPlugin.WSServer.LegacyHandler.HandleEvent(JObject e)
[23/11/2021 15:53:47] Error: Failed to process log line: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at RainbowMage.OverlayPlugin.EventDispatcher.DispatchEvent(JObject e)
   at RainbowMage.OverlayPlugin.EventSources.MiniParseEventSource.LogLineHandler(Boolean isImport, LogLineEventArgs args)
[23/11/2021 15:54:29] Error: Failed to send legacy WS message: System.InvalidOperationException: The current state of the connection is not Open.
   at WebSocketSharp.WebSocket.Send(String data)
   at WebSocketSharp.Server.WebSocketBehavior.Send(String data)
   at RainbowMage.OverlayPlugin.WSServer.LegacyHandler.HandleEvent(JObject e)
[23/11/2021 15:54:29] Error: Failed to process log line: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at RainbowMage.OverlayPlugin.EventDispatcher.DispatchEvent(JObject e)
   at RainbowMage.OverlayPlugin.EventSources.MiniParseEventSource.LogLineHandler(Boolean isImport, LogLineEventArgs args)

**Comment by seathasky** [comment]
A bunch of us run kargeru and cactbot etc without issues. If you are experiencing issues, I'd try reinstalling using the guide, this should not be happening. 

Otherwise:

Contact ngld: https://github.com/ngld/OverlayPlugin

**Comment by marzent** [comment]
If [these](https://ngld.github.io/OverlayPlugin/streamers) urls at the bottom also show the same behavior in Chromium and Firefox, then it’s most likely an OverlayPlugin issue (probably best to ask about that in the overlay-plugin section in the act discord)
However if it’s a BunnyHUD only problem feel free to open an issue in its own repo and I’ll try to look into it :)

**Comment by Tway1** [comment]
For what it's worth I installed Bunny-HUD by building your files using Xcode... I couldn't figure out another way of getting it to run. Not sure if that is the best way?

**Comment by marzent** [comment]
There should a ready-to-use app in the release section, but building yourself also works
